### PR TITLE
Remove old update client scripts

### PR DESCRIPTION
**Pull request by kivaisan**
For LmP ostree script is used instead.

### CODE REVIEW

**Comment by kivaisan** [comment]
cc: @JanneKiiskila @petedyerarm

**Review by petedyerarm — APPROVED** [review]
LGTM

**Review by JanneKiiskila — APPROVED** [review]

**Comment by JanneKiiskila** [comment]
Who's got merge rights?-)

**Comment by JanneKiiskila** [comment]
@esajaa ?

**Pull request merged**
