### PR TITLE
Reduce the logging level of edge-core to WARN

### PR DESCRIPTION
**Pull request by ygoyal18**

### CODE REVIEW

**Review by JanneKiiskila — APPROVED** [review]
This should hopefully reduce the logs to a more tolerable level.

**Comment by JanneKiiskila** [comment]
I have to say though, that if we had proper runtime logging - that would be perfect. This quite doesn't work together with FluentBit, but then again - mbed_trace was done for microcontroller based embedded systems. Might be worth studying if we could have a superset feature to nicely co-exists with both ideas. It already has some runtime filtering capability based on the trace class.

@TeroJaasko @artokin @ygoyal18 @AriParkkila

**Comment by ygoyal18** [comment]
@JanneKiiskila I agree. In order to get more logs from all the services around a specific event on the gateway, we should be able to dynamically control the logging level of the Edge processes. We are looking at supporting runtime configuration file option with edge core. Will prioritize it in coming releases - PELEDGE19-4162.

**Comment by TeroJaasko** [comment]
@JanneKiiskila one can control the log level at run time already with mbed_trace_config_set(). What functionality is missing there?

**Comment by JanneKiiskila** [comment]
Indeed, library point of view it actually looks quite good. We should compile it with _ALL and then just add the calling of the set in the startup and then expose a LwM2M resource to change it run-time.

**Pull request merged**
