### PR TITLE
Upgraded Edge Core recipe to pull latest release 0.18.0

### PR DESCRIPTION
**Pull request by ygoyal18**
PR created ahead of the release. Edge Core new release will be tagged in few hours.

### CODE REVIEW

**Review by esajaa — APPROVED** [review]

**Review by JanneKiiskila — APPROVED** [review]

**Comment by kivaisan** [comment]
@ygoyal18 Have you tried to build this yet in LmP environment? I would like to test one feature and I tried this but I see two different issues:
- For some reason Yocto tries to patch 0008-ordered-reboot.patch before initializing sub modules (so in this case it fails as lib/mbed-cloud-client is missing)
- I tested @esajaa 's hint to change SRC_URI as gitsm which initialized submodules automatically but now building fails as some warnings are treated as errors.

**Review by petedyerarm — APPROVED** [review]
LGTM

**Comment by ygoyal18** [comment]
Yes, I found out yesterday that 0.18.0 is not building because of the issues you mentioned above. Good to know that `gitsm` will fix the order to configuration. The other error is because of FORTIFY_SOURCE, will track it down today. i think its coming from mbedtls 2.25.

**Comment by ygoyal18** [comment]
Build is failing with these errors - 
```
19:50:17                   from /ws/build-factory/tmp-lmp/work/cortexa53-crypto-lmp-linux/mbed-edge-core-mx8mm/1.0-r0/git/lib/mbedtls/library/aesni.c:25:
19:50:17  /ws/build-factory/tmp-lmp/work/cortexa53-crypto-lmp-linux/mbed-edge-core-mx8mm/1.0-r0/recipe-sysroot/usr/include/features.h:397:4: error: #warning _FORTIFY_SOURCE requires compiling with optimization (-O) [-Werror=cpp]
19:50:17    397 | #  warning _FORTIFY_SOURCE requires compiling with optimization (-O)
19:50:17        |    ^~~~~~~
19:50:17  cc1: all warnings being treated as errors
```

this is because in glibc v2.29 it was introduced that **fortification requires optimization**. here is the [patch to features.h]( https://sourceware.org/git/?p=glibc.git;a=blobdiff;f=include/features.h;h=c700871ba574ae8e2690ea7c01ae0432cab86d08;hp=c347555ead27d4feccbd5edf1d234276377641f6;hb=05c2c9618f583ea4acd69b3fe5ae2a2922dd2ddc;hpb=4b30f61a1ea78de9b0e84a54fc6ee96ea70e6ed5)

Currently, we are by default creating a debug build `MBED_EDGE_CMAKE_BUILD_TYPE ?= "Debug"` which adds no optimization `-O0` when compiling mbedtls here - https://github.com/ARMmbed/mbedtls/blob/mbedtls-2.25.0/CMakeLists.txt#L186.. 

I am not sure where but fortification is set to this `-D_FORTIFY_SOURCE=2` and hence its breaking. I think it is Yocto which is enabling it..

The way we solved this problem earlier in mbed-edge project is to add a condition that if fortification is <=0 then do not optimize - https://github.com/PelionIoT/mbed-edge/blob/master/CMakeLists.txt#L88 

According to this - https://stackoverflow.com/a/16604146/12488057, fortification is secure but risky. Does anyone know more about this to know if we should keep it or turn it off?  @esajaa @kivaisan @petedyerarm @x85446 

BTW, if we create a Release build then its not failing.

**Comment by ygoyal18** [comment]
Found something - Security flags are being set in Yocto environment. They are described here - https://git.yoctoproject.org/cgit.cgi/poky/plain/meta/conf/distro/include/security_flags.inc 

A variable called `lcl_maybe_fortify` is setting `-D_FORTIFY_SOURCE=2` if not defined and if `-O2` is set. By explicitly defining this variable in our recipe `lcl_maybe_fortify = '-D_FORTIFY_SOURCE=0'` solves this issue. 

Is it wise to turn off FORTIFY_SOURCE, i am not sure. Comments - @petedyerarm @x85446 @esajaa @kivaisan ? 
My thoughts are that if the project source is not compiled and tested with FORTIFY_SOURCE flag then we should do the same. According to my understanding, if project wants to handle fortification then they should explicitly define it in the project's CMake along with the optimization flags.

**Review by esajaa — APPROVED** [review]

**Comment by esajaa** [comment]
@kivaisan You could give a try to these changes

**Comment by kivaisan** [comment]
Compilation works now.

**Pull request merged**
