### PR TITLE
Simplify partition layout.

### PR DESCRIPTION
**Pull request by petedyerarm**
Removed the unused partitions.
Link userdata to /var/rootdirs/userdata.

### CODE REVIEW

**Comment by JanneKiiskila** [comment]
Do we need some changes also to meta-pelion-edge? I would assume so, we could simply the wks.in and fstab -files.

**Comment by JanneKiiskila** [comment]
Title has typo, s**i**mpilify. @petedyerarm  - otherwise Looks Good To Me.

**Review by JanneKiiskila — CHANGES_REQUESTED** [review]
Fix the typo in the git commit/PR subject (simplyfy -> simplify).

**Review by JanneKiiskila — APPROVED** [review]

**Comment by JanneKiiskila** [comment]
NOTE! Needs to go in at https://github.com/PelionIoT/meta-pelion-edge/pull/289.

**Review by esajaa — APPROVED** [review]

**Review by kivaisan — APPROVED** [review]
LGTM. Tested FOTA on RPI4.

**Pull request merged**
