### PR TITLE
Specify MBED_CLOUD_CLIENT_FOTA_LINUX_CONFIG_DIR.

### PR DESCRIPTION
**Pull request by petedyerarm**
Replace the defines for indivdual FOTA_LINUX files with a single define
providing the containing DIR instead.

### CODE REVIEW

**Review by ygoyal18 — APPROVED** [review]
LGTM

**Review by JanneKiiskila — APPROVED** [review]

**Review by JanneKiiskila — CHANGES_REQUESTED** [review]
Could we just drop the whole MBED_CLOUD -thing there and just have it as CLIENT_FOTA_...

**Review by davidsaada — APPROVED** [review]
LGTM.

**Comment by davidsaada** [comment]
> Could we just drop the whole MBED_CLOUD -thing there and just have it as CLIENT_FOTA_...

@JanneKiiskila This is a wide change that needs to be done in MCC repo, not here.

**Review by JanneKiiskila — APPROVED** [review]

**Pull request merged**
