### PR TITLE
Updated Parsec SE driver 0.5.0 recipe - Locked down the crates

### PR DESCRIPTION
**Pull request by ygoyal18**
Signed-off-by: Anton Antonov <Anton.Antonov@arm.com>

### CODE REVIEW

**Review by petedyerarm — APPROVED** [review]
LGTM

**Comment by ygoyal18** [comment]
This fixes compiling parsec-se-driver in 2.4. I have manually verified this patch.

**Comment by petedyerarm** [comment]
I have also manually verified this PR.

**Comment by kivaisan** [comment]
I was trying a clean Edge 2.4 build but it still failed to crate issues even with this PR cherry-picked. @petedyerarm promised to check the issue.

**Comment by petedyerarm** [comment]
> I was trying a clean Edge 2.4 build but it still failed to crate issues even with this PR cherry-picked. @petedyerarm promised to check the issue.

I'm checking it but what you see is a different issue when building the parsec-service, not the parsec-se-driver. 
The problem this PR addresses should only present if you have MBED_EDGE_CORE_CONFIG_PARSEC_TPM_SE_SUPPORT="ON"

**Comment by kivaisan** [comment]
> 
> 
> > I was trying a clean Edge 2.4 build but it still failed to crate issues even with this PR cherry-picked. @petedyerarm promised to check the issue.
> 
> I'm checking it but what you see is a different issue when building the parsec-service, not the parsec-se-driver.
> The problem this PR addresses should only present if you have MBED_EDGE_CORE_CONFIG_PARSEC_TPM_SE_SUPPORT="ON"

I created a new work area and now build succeeded nicely.

**Pull request merged**
